### ISSUE TITLE
Some potential problems in Code implement (may be I am wrong) 

### ISSUE THREAD

**Issue by collegestu1231** [skewondr/FoLiBi#2]
In the line 665 of modules.py,the final score is calculated as: scores += score_mask,which means the first picture 
![first_picture](https://github.com/skewondr/FoLiBi/assets/106469619/38e4eaa9-a817-4203-b5ff-e233a44bfb8b)
but in the paper,the final score is calculated as the second picture: 
![1713940541160](https://github.com/skewondr/FoLiBi/assets/106469619/92298de4-f2b8-4ccd-9d02-21a5d49866e7),
"So, should this part be changed to scores += score_mask / math.sqrt(d_k)?"

**Comment by skewondr** [comment]
Hello, collegestu1231, thank you for visiting my repository. 

To answer the question, please check the equation (2) as well as (3) in my paper [https://dl.acm.org/doi/10.1145/3583780.3615191](url)

the beta has -q_tK, so the final numerator becomes exp(...)*q_tK / root(d)

Thank you.

**Comment by collegestu1231** [comment]
Thank you！！！
