### ISSUE TITLE
About the role of variables in the code

### ISSUE THREAD

**Issue by zhijiezhong** [skewondr/FoLiBi#3]
Hello, skewondr. I'm happy to see this very interesting paper. I am looking at your code and I have some questions for you about variables in code.

self.de = de_type.split('_')[0]
self.token_num = int(de_type.split('_')[1])
self.choose_enc = choose_enc
if self.de.startswith(("sde", "random", "alibi-sde", "rotary-sde")):

What do the following variables do?
self.de, self.token_num, self.choose_enc, ("sde", "random", "alibi-sde", "rotary-sde")

Looking forward to your reply, thanks!

**Comment by zhijiezhong** [comment]
The original akt code doesn't have these, so I'm a little unsure what they do.

**Comment by skewondr** [comment]
Hello zhijiezhong, thank you for interest in my paper.
I wrote those codes for my personal experiments.
It is far from the paper's content, but you can use it if you want to experiment with 'question difficulty embedding' 

When data pre-processing, I calculate each question's accuracy rate (correct count/total count) in each dataset, which refers to difficulty information.
please check (https://github.com/skewondr/FoLiBi/blob/folibi/data_loaders.py)

**Comment by zhijiezhong** [comment]
Thank you!
